
const TARGET_TYPE_ATTR = 0 as const
const TARGET_TYPE_GLUE_REL = 1 as const
const TARGET_TYPE_HEAVY_REQUESTER = 2 as const
const TARGET_TYPE_UNIQ_REL_BY_ATTR = 3 as const
const TARGET_TYPE_ROUTE_MATCHING = 4 as const

export default {
  TARGET_TYPE_ATTR,
  TARGET_TYPE_GLUE_REL,
  TARGET_TYPE_HEAVY_REQUESTER,
  TARGET_TYPE_UNIQ_REL_BY_ATTR,
  TARGET_TYPE_ROUTE_MATCHING,
}
