
const TARGET_TYPE_ATTR = 0
const TARGET_TYPE_GLUE_REL = 1
const TARGET_TYPE_HEAVY_REQUESTER = 2
const TARGET_TYPE_UNIQ_REL_BY_ATTR = 3
const TARGET_TYPE_ROUTE_MATCHING = 4

export default {
  TARGET_TYPE_ATTR,
  TARGET_TYPE_GLUE_REL,
  TARGET_TYPE_HEAVY_REQUESTER,
  TARGET_TYPE_UNIQ_REL_BY_ATTR,
  TARGET_TYPE_ROUTE_MATCHING,
}
