import {
  TARGET_TYPE_ATTR,
  TARGET_TYPE_HEAVY_REQUESTER,
  TARGET_TYPE_UNIQ_REL_BY_ATTR,
  TARGET_TYPE_ROUTE_MATCHING
} from './target_types.types'

export default {
  TARGET_TYPE_ATTR,
  TARGET_TYPE_HEAVY_REQUESTER,
  TARGET_TYPE_UNIQ_REL_BY_ATTR,
  TARGET_TYPE_ROUTE_MATCHING,
}
